[package]
name = "polytext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.6.0"
nalgebra = "0.32.3"
strum = { version = "0.26.1", features = ["derive"] }
tailcall = "1.0.1"
